# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb08cb006024c233c44f7563751ebe1eb5b021d2f1181c85ccf86941b15f2ebff8a624d38ab57f6a0ceccaba6c4d12637146cba0bd79953a7b73ca6b78e7d1be

test:
  secret_key_base: 41a153ff81d6a36ff6a7ba6eb3a4a8663c0d3c81bd0a6db3837ef592ab9425160a7dd5f8c75bf534114cad962f8a1c93cee373f8eee2c122844f706dca15c732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
